[package]
name = "dclient"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = [ "derive", "cargo" ] }
tokio = { version = "1.36.0", features = ["full"] }
anyhow = "1.0"
lazy_static = "1.4"
hetu_log = {path = "../hetu_log" }
keystore = { path = "../keystore"}